spring:
  datasource:
    username: music-forum
    password: music-forum
    url: jdbc:postgresql://localhost:5433/users-db
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: "update"

application:
  jwt:
    secret: "I'll see you on the dark side of the moon"
    expiration: 86400000