spring:

  application:
    name: report-server

  profiles:
    default: default

  config:
    import: "optional:configserver:http://localhost:7777"

  data:
    mongodb:
      uri: "${spring.data.mongodb.uri}"

server:
  servlet:
    context-path: /report-server
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
